### ISSUE TITLE
Bug with Nuclide's Tree View

### ISSUE THREAD

**Issue by keplersj** [cdonohue/pristine-ui#12]
I get a weird bug with this theme while using Nuclide's Tree View when opening a directory in the tree.

Before:
<img width="304" alt="screen shot 2017-07-13 at 6 12 35 pm" src="https://user-images.githubusercontent.com/594124/28193013-2795675c-67f7-11e7-983c-ad440b4cd248.png">

After:
<img width="293" alt="screen shot 2017-07-13 at 6 12 46 pm" src="https://user-images.githubusercontent.com/594124/28193015-2bc82aee-67f7-11e7-9545-d6c11e3ccaf3.png">

It seems that the theme is move just one list item too many to the right when the directory above it is opened. I could be totally wrong but that seems to be what's happening.

Ninja Edit: Just double checked and the bug does not occur when One Dark is enabled.

**Comment by cdonohue** [comment]
Thank you for finding this @keplersj . I'll take a look.

**Comment by irrationalistic** [comment]
I came across this as well. Looks like it's this bit: https://github.com/cdonohue/pristine-ui/blob/e9025d6fe55bd7f39dcb0150e1198cdd9d303a18/styles/tree-view.less#L51

I think that just adds a dot after a file, but I can't tell the purpose. You could either remove it or set the container to position relative and position the ::after absolute within!

**Comment by cdonohue** [comment]
Thanks for the research @irrationalistic . I should have some time this weekend to take a look.

**Comment by cdonohue** [comment]
@keplersj @irrationalistic I have made a change to the ui theme that excludes `nuclide` from the tree-view styling. There would have to be a different set of styles to govern the markup that `nuclide` produces since things seem to be flatter rather than nested, as far as the relationship of the elements. 

I'll continue to look into supporting this using a separate styling file specific to `nuclide` as a later feature. 

Thank you both again for looking into this.

**Comment by keplersj** [comment]
Thanks @cdonohue! I'm definitely going to miss those animations but it's working now.
