### ISSUE TITLE
Request: Theme for VS Code

### ISSUE THREAD

**Issue by smith-phillip-m** [cdonohue/pristine-ui#17]
This is my favorite theme in Atom. Are you able to make this theme available for VS Code?

**Comment by cdonohue** [comment]
@smith-phillip-m that's a great idea. Although, it seems that `vs-code` has a different support model for ui elements in the editor.

Pristine UI makes some file tree style modifications and adapts to the user's syntax theme by using the syntax foreground and background colors to build upon. Atom makes this super easy due to it exposing the `less` variables used. 

VS Code allows for customizing syntax colors, but only [recently](https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme) opened up theming for other parts of the ui _outside_ of the editor window. These are only color changes, so no additional elements could be added (tree view folder scope lines, etc). Coloring ui elements becomes an easier task, but the ui cannot adapt to a different set of colors when a user changes their syntax theme.

As a VS Code user, I personally would settle on a syntax theme, and then add different colors in my user settings file `Cmd+,` until the UI complimented the syntax.

I hope that helps, and thank you for your kind words!

**Comment by smith-phillip-m** [comment]
I didn't realize the difference in theme implementations between the two.
Thank you for your time.
