### ISSUE TITLE
Light UI Theme

### ISSUE THREAD

**Issue by ramskow** [cdonohue/pristine-ui#5]
I think this theme is a good solution to the existing [One Dark UI](https://atom.io/themes/one-dark-ui) theme, you've improved it and did a great job. I think it would be nice if there was a [One Light UI](https://atom.io/themes/one-light-ui) theme aswell and I suppose that people will start changing between the two alot based on their syntax themes. Besides that I would love it aswell and use both!

**Comment by cdonohue** [comment]
Great suggestion @Ramy! I'll take a look to see what it would take to make this theme more adaptable to light syntax themes.

**Comment by onetrev** [comment]
Hello! Sorry for the quick question on a closed item, but just wondering since this was just recently closed, is that because you have / will soon add light syntax support, or just not going to be able to support it? Seems like it would take instead a different UI theme altogether, as from my experience Atom UI themes are either one or the other. It would be great if the same UI though could have either option. 

Thanks either way!

**Comment by cdonohue** [comment]
@onetrev Thanks for asking and great question. @Ramy actually closed this (probably due to little activity). I plan on looking into it and think it _is_ possible. The idea I have is to use the theme settings and have a box to toggle light/dark. Then, the underlying colors will check contrast ratios and produce a `light` or `dark` theme. I'll re-open this and think about it some more. Thank you for asking!

**Comment by cdonohue** [comment]
I think this is best left to solving with having another theme. Unless anyone wants to try and solve it. PRs welcome 😄
