### ISSUE TITLE
Wrong directory tree

### ISSUE THREAD

**Issue by ghost** [cdonohue/pristine-ui#6]
Hello, 
 I have updated my Atom v1.17.0 and Pristine v1.0.15 and the Directory tree is displaying a wrong indentation, when I open some directory it collapses it's bellowing directory, take a look at the screenshot for more details. 

Wrong indentation
![another_directory_wrong_tree](https://cloud.githubusercontent.com/assets/17497134/26318791/ba653a40-3ef2-11e7-85c9-c747e7d8e564.png)

Right One
![right_tree](https://cloud.githubusercontent.com/assets/17497134/26318985/9811e3ca-3ef3-11e7-9f9d-7aee92aa2df2.png)

**Comment by cdonohue** [comment]
@thiagopecanha is your repo public? Or, rather, could you make an example project with the structure above so that I can troubleshoot?

**Comment by grego3** [comment]
@cdonohue I've also been seeing this.

I've been able to reproduce with [Drupal's public mirror repo](https://github.com/drupal/drupal).

I opened that repo in Atom, then expanded the `core` directory, then the `modules` dir, then the `aggregator` dir, and finally the `migration_templates` dir. `src` now looks as though it's a child of `migration_templates` but only when `migration_templates` is expanded (I've attached screenshots below).

Running Atom 1.17.0 and Pristine 1.0.15.

`migration_templates` collapsed:
![screen shot 2017-05-23 at 4 57 01 pm](https://cloud.githubusercontent.com/assets/9215873/26375990/e77cb71a-3fd8-11e7-8c99-0734311358bc.png)

`migration_templates` expanded:
![screen shot 2017-05-23 at 4 57 14 pm](https://cloud.githubusercontent.com/assets/9215873/26376017/fe061166-3fd8-11e7-9e75-fff41f1f493b.png)

**Comment by cdonohue** [comment]
Thanks for the info @grego3 I'll take a look.

**Comment by cdonohue** [comment]
@thiagopecanha @grego3 I've cloned the `drupal` repo and expanded the structure as you mentioned. However, I'm not seeing the same results that you posted. Perhaps another package or custom style is altering that?

<img width="323" alt="screen shot 2017-05-24 at 3 08 19 am" src="https://cloud.githubusercontent.com/assets/1928846/26393155/925df982-402e-11e7-91bb-0479ff86d749.png">

**Comment by grego3** [comment]
@cdonohue Interesting. Thanks for taking a look!

I'll debug and see if I can find the issue here...

**Comment by cdonohue** [comment]
@grego3 let me know what I can do to help out

**Comment by grego3** [comment]
@cdonohue Not a solve, but I've found a bit more info about this bug.

First, I disabled all community packages. Additionally, I use [Spectacle](https://www.spectacleapp.com/) for window management on my laptop. When I open Atom, the directory tree looks good (no nesting/appearance issues). When I use the Spectacle hotkey to make the Atom window fullscreen, the directory tree resizes to fit the new window size and I start seeing the issue described above. This doesn't seem to happen for the Atom Dark theme, which makes me think this may be related to Pristine's spacious layout and Atom's recent UI updates.

I'll continue looking for a solution to this, but at least it seems like an edge case.

**Edit**: This also happens when I resize the Atom window without using Spectacle (manually by clicking the edges of the window and dragging).

**Comment by cdonohue** [comment]
Aha! I see. I've personally moved to using `One Dark` myself and just using the custom styles for `modal` and `tree-view` styles 😄 (Maybe I should just make those packages of their own, rather than trying to keep up an entire UI theme)

I'll troubleshoot some more and post back. Thank you for the info @grego3 !

**Comment by ghost** [comment]
@cdonohue , so I've got something else:
 When I changed Pristine Layout mode to `compact` it worked like a charm, however on  `auto` and `spacious` it's not.

Another thing: right now I am using Atom on `OSx Sierra 10.12.5`, when I opened the issue, it was on `ArchLinux with KDE`.

One more thing: it's a `Rails` project structure, you could get one with: `rails new project` or clone one of mine repository.

Compact
![captura de tela 2017-05-24 as 13 03 39](https://cloud.githubusercontent.com/assets/17497134/26413849/b3814a1a-4083-11e7-83a5-e293c500674a.png)

Auto or Spacious
![captura de tela 2017-05-24 as 13 04 00](https://cloud.githubusercontent.com/assets/17497134/26413894/cf3eb6ca-4083-11e7-8724-ff3728c175c8.png)

**Comment by cdonohue** [comment]
That makes sense, @thiagopecanha, seeing as how `One Dark` seemed to move away from the `Spacious` settings. I'll look into removing that :)

**Comment by zachcoss** [comment]
Also having the same issue when Pristine is set to UI Theme

**Comment by cdonohue** [comment]
@zachcoss this ui-theme is getting an update that resolves most of the issues with some recent atom version changes (including this issue). I'll post back up here when that goes live. Probably tomorrow or Wednesday.

**Comment by cdonohue** [comment]
@thiagopecanha @zachcoss can you verify that this is still an issue? The latest version, `1.1.0` should address this.

**Comment by ghost** [comment]
@cdonohue over here, working as expected.
